### ISSUE TITLE
Most of our SQLite schema is not parseable

### ISSUE THREAD

**Issue by bradfitz** [rqlite/sql#18]
Tailscale's SQLite schema fails to parse with this project's parser.

This repro runs in the Go playground: https://go.dev/play/p/-UUNRSKBBzr

... which says `parsed 8 out of 83`

If you flip the bool to remove comments with a regexp, it jumps to `parsed 55 out of 83`.

Looks like the remaining issues are around generated columns and constraints.

I sent #17 for the comments to start.

/cc @otoolep @benbjohnson

**Comment by benbjohnson** [comment]
I added support for comment parsing here: https://github.com/rqlite/sql/pull/19

**Comment by benbjohnson** [comment]
```
CREATE TABLE T2 (
	C1   TEXT     PRIMARY KEY,  -- comment
	C2 TEXT     NOT NULL DEFAULT "discokey:0000000000000000000000000000000000000000000000000000000000000000",

 -- comment
 -- comment
 -- comment
 -- comment
	C3 INTEGER NOT NULL DEFAULT FALSE, -- comment

 -- comment
	C4  INTEGER NOT NULL DEFAULT (strftime('%s', 'now')), -- comment
	C5 INTEGER NOT NULL DEFAULT -1
)
```

Regarding this one, the problem is that a double-quoted string is used as the default value. It's sorta legal but SQLite shows a warning message v3.27.0 and it outright disables them as of v3.41.0 in the CLI. I'm inclined to leave the behavior as-is but I'm open to other thoughts. 

https://www.sqlite.org/quirks.html#double_quoted_string_literals_are_accepted

**Comment by benbjohnson** [comment]
I added support for the `->` and `->>` operators here: https://github.com/rqlite/sql/pull/20

**Comment by otoolep** [comment]
All the new PRs merged -- thanks.

https://github.com/rqlite/sql/pull/21 merged too.

**Comment by benbjohnson** [comment]
Ok, that was a flurry of PRs :) 

It's down to 2 failing cases now:

## T67

I added `COLLATE` but it looks like it's not working for `UNIQUE` table constraints yet. I can fix that but I need to take off at the moment. The issue is that it's parsing column names instead of `indexed-column` [here](https://github.com/rqlite/sql/blob/5322d37e118c57b1690a4877cda2a06a3468d753/parser.go#L529-L533). It's not a hard fix as there's already a `parseIndexedColumn()` function.

## T68

The first issue is that the table constraints don't all have commas between them. The railroad diagram shows a required comma but I guess the SQLite parser isn't as strict.

<img width="755" alt="Screenshot 2024-03-10 at 4 54 17 PM" src="https://github.com/rqlite/sql/assets/118015/8fe7dc7c-3e53-42bf-9fc6-8a1ea1d69133">

If you add the comma then it fails on `==` which I didn't realize was legal SQL. The fix here is to just parse `==` as an `EQ` token and it should work.

**Comment by bradfitz** [comment]
> Regarding this one, the problem is that a double-quoted string is used as the default value. It's sorta legal but SQLite shows a warning message v3.27.0 and it outright disables them as of v3.41.0 in the CLI. I'm inclined to leave the behavior as-is but I'm open to other thoughts.

We've compiled with with the recommended `-DSQLITE_DQS=0` since 2021 (https://github.com/tailscale/sqlite/commit/86f2bd355ded9c0a62c9fbce442b7242c1ea0042) but it doesn't seem to affect the DEFAULT value `string-literal` at all. I've just tried compiling a number of ways, including trying to set SQLITE_DBCONFIG_DQS_DDL to 0, but then I just get warnings because it's already set by SQLITE_DQS: 

```
/* The SQLITE_DQS compile-time option determines the default settings
** for SQLITE_DBCONFIG_DQS_DDL and SQLITE_DBCONFIG_DQS_DML.
**
**    SQLITE_DQS     SQLITE_DBCONFIG_DQS_DDL    SQLITE_DBCONFIG_DQS_DML
**    ----------     -----------------------    -----------------------
**     undefined               on                          on
**         3                   on                          on
**         2                   on                         off
**         1                  off                          on
**         0                  off                         off
**
** Legacy behavior is 3 (double-quoted string literals are allowed anywhere)
** and so that is the default.  But developers are encouraged to use
** -DSQLITE_DQS=0 (best) or -DSQLITE_DQS=1 (second choice) if possible.
*/
```

~~I can reproduce the failure with a modern CLI but I can't yet make a program linking sqlite enforce it.~~

**Comment by bradfitz** [comment]
Even the CLI doesn't enforce it in column-constraint DEFAULT literal-value. But does for INSERT, etc:

```
$ ./tool/sqlite3
SQLite version 3.43.1 2023-09-11 12:01:27
Enter ".help" for usage hints.
Connected to a transient in-memory database.
Use ".open FILENAME" to reopen on a persistent database.
sqlite> CREATE TABLE T (A TEXT, B TEXT DEFAULT "foo");
sqlite> INSERT INTO T (A) VALUES ("v");
Parse error: no such column: v
  INSERT INTO T (A) VALUES ("v");
              error here ---^
sqlite> INSERT INTO T (A) VALUES ('v');
sqlite> SELECT * FROM T;
v|foo
sqlite> .dbconfig
          defensive on
            dqs_ddl off
            dqs_dml off
        enable_fkey off
        enable_qpsg off
     enable_trigger on
        enable_view on
     fts3_tokenizer off
 legacy_alter_table off
 legacy_file_format off
     load_extension on
   no_ckpt_on_close off
     reset_database off
  reverse_scanorder off
    stmt_scanstatus off
        trigger_eqp off
     trusted_schema off
    writable_schema off
sqlite> 
```

(from @raggi)

**Comment by benbjohnson** [comment]
@bradfitz Ok, I think I got everything fixed. If you add commas between the table constraints for T68 & T69 then everything should pass. Let me know if you have any more issues.

**Comment by benbjohnson** [comment]
re: DEFAULT DQS value, I fixed it in #28

**Comment by bradfitz** [comment]
Thanks for all the fixes, @benbjohnson! We now have a test that locks in rqlite/sql parsability so maybe we'll stop doing crazy stuff now :)

**Comment by otoolep** [comment]
@bradfitz -- can you tell us what you're using the Parsing code for?

**Comment by otoolep** [comment]
And yes, thanks to @benbjohnson for the latest fixes.
