### ISSUE TITLE
Can't parse CREATE TABLE with column named Key

### ISSUE THREAD

**Issue by bradfitz** [rqlite/sql#29]
sqlite accepts a column named `Key`:

```
% ./tool/sqlite3
SQLite version 3.43.1 2023-09-11 12:01:27
Enter ".help" for usage hints.
Connected to a transient in-memory database.
Use ".open FILENAME" to reopen on a persistent database.
sqlite> create table T (Key TEXT);
sqlite> 
```

But this doesn't: https://go.dev/play/p/smHhyP2dNDb

=> `error: 1:17: expected column name, CONSTRAINT, or right paren, found 'KEY'`

(related to #18 in that I found this once I ran it against unredacted column names :))

/cc @benbjohnson

**Comment by benbjohnson** [comment]
hmm, that's weird. `KEY` is listed as a keyword in [this list](https://sqlite.org/lang_keywords.html) so that should fail. I'm not sure the rhyme or reason for what keywords SQLite accepts or not for column names. For example, `abort` and `key` work as column names but not `create` or `table`.

I generated a list of acceptable keywords. Maybe I'll just whitelist them?

```
ABORT
ACTION
AFTER
ALWAYS
ANALYZE
ASC
ATTACH
BEFORE
BEGIN
BY
CASCADE
CAST
COLUMN
CONFLICT
CROSS
CURRENT
CURRENT_DATE
CURRENT_TIME
CURRENT_TIMESTAMP
DATABASE
DEFERRED
DESC
DETACH
DO
EACH
END
EXCLUDE
EXCLUSIVE
EXPLAIN
FAIL
FILTER
FIRST
FOLLOWING
FOR
FULL
GENERATED
GLOB
GROUPS
IF
IGNORE
IMMEDIATE
INDEXED
INITIALLY
INNER
INSTEAD
KEY
LAST
LEFT
LIKE
MATCH
MATERIALIZED
NATURAL
NO
NULLS
OF
OFFSET
OTHERS
OUTER
OVER
PARTITION
PLAN
PRAGMA
PRECEDING
QUERY
RAISE
RANGE
RECURSIVE
REGEXP
REINDEX
RELEASE
RENAME
REPLACE
RESTRICT
RIGHT
ROLLBACK
ROW
ROWS
SAVEPOINT
TEMP
TEMPORARY
TIES
TRIGGER
UNBOUNDED
VACUUM
VIEW
VIRTUAL
WINDOW
WITH
WITHOUT
```

**Comment by benbjohnson** [comment]
@bradfitz I pushed up the change in https://github.com/rqlite/sql/pull/30 and it's merged. 👍
